destination: ./_site
source:      .
lsi:         false
server_port: 4000
pygments:    true
markdown:    rdiscount
exclude:     [.git]
permalink:   /:title.html
url:         http://mapbox.github.com/wax
baseurl:     /wax
rdiscount:
  extensions: [smart]
