destination: ./_site
source:      .
lsi:         false
server_port: 4000
pygments:    true
markdown:    kramdown
exclude:     [.git]
permalink:   /:title.html
url:         https://github.com/tilemill-project/wax
baseurl:     /wax
rdiscount:
  extensions: [smart]
